-- NCM Branch Rates Update Script
-- Generated from official NCM rate card PDF
-- Source: Narayanghat to all 561 branches
-- Columns: shipping_rate = Door Delivery, office_pickup_rate = Branch Delivery

-- ============================================
-- TIER 1: Rs. 120 / Rs. 70 (Nearby Areas)
-- ============================================
UPDATE ncm_branches SET shipping_rate = 120, office_pickup_rate = 70 
WHERE branch_name IN (
  'NARAYANGHAT',
  'BIRGUNJ',
  'HETAUDA',
  'KAWASOTI',
  'TANDI',
  'GAIDAKOT',
  'KALAIYA',
  'NIJGADH',
  'SIMARA',
  'CHANDRANIGAHAPUR',
  'DALDALE',
  'CHORMARA',
  'RAJAHAR',
  'MANAHARI',
  'ARUNKHOLA',
  'DUMKIBAS',
  'GAUR',
  'SHAKTIKHOR',
  'POKHARIYA',
  'KURINTAR',
  'BHANDARA',
  'GARUDA',
  'KHAIRAHANI',
  'CHANAULI',
  'BASTANTAPUR BAZAR',
  'BASTIPUR MAKAWANPUR',
  'AMLEKHGUNJ',
  'MAULAPUR',
  'MEGHAULI',
  'JAGATPUR',
  'DEVGHAT',
  'JUGEDI CHITWAN',
  'SARDI',
  'DEWAHI GONAHI',
  'SAMANPUR',
  'BARIYARPUR',
  'SIMRANGADH',
  'BADNIHAR',
  'HARNAIYA',
  'MATSARI',
  'JAGARNATHPUR',
  'SEDHAWA',
  'KALIKAMAI',
  'PAKAHA MAINPUR',
  'PATERWA SUGAULI',
  'SARUWATHA',
  'MUNGLING',
  'BAHAURI PIDARI',
  'BINDABASINI',
  'BHISAWA SHIKTA',
  'DHAUBINI',
  'JANGAL SAHIYA',
  'KATAHARIYA',
  'FATUWA HARSAHA',
  'PACHARAUTA',
  'BISHRAMPUR',
  'DEVTAL BENAULI',
  'KARAIYAMAI',
  'PARWANIPUR',
  'PHETA BAZAR',
  'PRASAUNI',
  'JHYALBAS',
  'BRINDABAN',
  'SAKHUWA PRASAUNI',
  'BARAGADHI',
  'LOTHAR',
  'RAMNAGAR',
  'KRISHNANAGAR MADI'
);

-- ============================================
-- TIER 2: Rs. 170 / Rs. 120 (Valley/Major Cities)
-- ============================================
UPDATE ncm_branches SET shipping_rate = 170, office_pickup_rate = 120 
WHERE branch_name IN (
  'TINKUNE',
  'BUTWAL',
  'BHAIRAHAWA',
  'BIRATNAGAR',
  'ITAHARI',
  'POKHARA',
  'BANEPA',
  'LEKHNATH',
  'DAMAULI',
  'DUMRE',
  'MANIGRAM',
  'DHULIKHEL',
  'PANAUTI',
  'NAYA BUSPARK',
  'NEWROAD',
  'JOGIKUTI',
  'ANBUKHAIRENI',
  'SURYABINAYAK',
  'PAME',
  'PURANCHAUR',
  'NAGARKOT',
  'DHARKE',
  'KAPAN',
  'SATDOBATO',
  'LUBHU',
  'CHAPAGAUN',
  'THANKOT',
  'SWOYAMBHU',
  'BASUNDHARA',
  'BUDHANILKANTHA',
  'SANKHU',
  'NAYA THIMI',
  'GODAWARI',
  'KAVRESTHALI',
  'SUNDARIJAL',
  'TOKHA',
  'NETACHOWK',
  'THUTIPIPAL',
  'BAGMARA',
  'BANSBARI MORANG',
  'TIGER TOP HILL',
  'CHABAHIL',
  'DULEGAUDA',
  'KALANKI'
);

-- ============================================
-- TIER 3: Rs. 175 / Rs. 125 (Regional)
-- ============================================
UPDATE ncm_branches SET shipping_rate = 175, office_pickup_rate = 125 
WHERE branch_name IN (
  'DHARAN',
  'BIRTAMOD',
  'BHADRAPUR',
  'JANAKPUR',
  'DHALKEBAR',
  'DAMAK',
  'BIRATCHOWK',
  'URLABARI',
  'RAJBIRAJ',
  'LAHAN',
  'TANSEN',
  'SUNAWAL',
  'BARDAGHAT',
  'INARUWA',
  'BAGLUNG BAZAR',
  'BENI',
  'BARDIBAS',
  'WALING',
  'KUSHMA',
  'KAKARBHITTA',
  'DHULABARI',
  'SURUNGA',
  'TAULIHAWA',
  'CHANDRAUTA',
  'RANGELI',
  'PARASI',
  'PUTALIBAZAR',
  'LALBANDI',
  'PHARSATIKAR',
  'GAIGHAT',
  'BELBARI',
  'GAURADAHA',
  'DUHABI',
  'BUDHABARE',
  'GORKHA BAZAR',
  'TAMNAGAR',
  'JALESHWOR',
  'SHARANAMATI',
  'GOLBAZAR',
  'KRISHNANAGAR',
  'MURGIYA',
  'AMUWA',
  'BELDANGI',
  'JHILJHILE',
  'HEMJA',
  'KANCHIBAJAR',
  'SAKUWA MAHENDRANAGAR',
  'PHEDIKHOLA',
  'KOTIHAWA',
  'LUMBINI',
  'MOTIPUR',
  'BANIYANI',
  'GAURIGANJ',
  'RAJGADH',
  'MADHUMALLA',
  'PATHARI',
  'HARIWON',
  'GALYANG',
  'MALANGWA',
  'GOPIGUNJ JAMUNIYA',
  'DHAKDAI',
  'FATTEPUR',
  'RUPNAGAR',
  'KHUDUNABARI',
  'LETANG',
  'BHIMAD',
  'GAUSHALA MAHOTTARI',
  'SIRAHA',
  'KALABANJAR',
  'CHATARA',
  'JITPUR CHARNUMBER',
  'MIRCHAIYA',
  'BAHUNDANGI',
  'SHIVAGUNJ',
  'PATICHAUR',
  'BAYALBAS',
  'KHAIRENI RUPANDEHI',
  'BARAHATHAWA',
  'DAMRABHITTA',
  'KERKHA BAZAR',
  'JUGLE',
  'CHARAALI',
  'KERABARI MORANG',
  'AMARDAHA',
  'BARJU',
  'ODARI',
  'RAMAILO',
  'LAUKAHI',
  'BELDAHA',
  'HAKIM CHOWK',
  'BIRGUNJ CHOWK',
  'HALDIBARI',
  'BHIMAN',
  'KHIMTI',
  'SANISCHARE',
  'NEPALTAR UDAYAPUR',
  'BELSOT',
  'PANMARA',
  'MADI PALPA',
  'GOKULGANGA',
  'DUMARI KALYANPUR',
  'ARNAHA',
  'SANGRAMPUR',
  'HANSPUR KATHPULLA',
  'BALAWA',
  'JHAPA BAZAR',
  'SARANGKOT',
  'EKADARA',
  'SAPAHI',
  'TULSIYAHI',
  'PIPRA',
  'RAMNAGAR',
  'MAINAPOKHARI',
  'BHANGAHA',
  'BHAWANIPUR',
  'BATESHWOR',
  'MANARA',
  'BODEBARSAIN',
  'PATO',
  'MAHULI',
  'HAKPARA',
  'BARIYARPATTI',
  'BISHNUPUR SAPTARI',
  'LAXMIPUR PATARI',
  'NARAHA',
  'NAWARAJPUR',
  'RUPANI',
  'MAHESHWORI',
  'DIMAN',
  'DEWANGANJ',
  'AURABANI',
  'HARINAGARA',
  'JAHADA',
  'KATAHARI MORANG',
  'HARAIYA RUPANDEHI',
  'AARUGHAT',
  'SINGA TATOPANI',
  'SAKHADA CHHINNAMASTA',
  'TOPA BAZAR',
  'CHANHI BAZAR',
  'BHOKRAHA',
  'PRAKASHPUR',
  'BAHUNI',
  'BALARA',
  'HARIPURWA',
  'TARAPATTI SIRSIYA',
  'AURAHI DHANUSHA',
  'BRAHAMPURI',
  'CHAKRAGHATTA SARLAHI',
  'NADHIMAN',
  'DHANKAUL',
  'DHANAUJI',
  'KHAJURI CHANHA',
  'KAUDENA',
  'PARSA SARLAHI',
  'MAHOTTARI',
  'SONAMA',
  'LABANI',
  'BASABASAHI',
  'BAIDAULI',
  'SURYAPURA',
  'MAHASHILA LUNKHU',
  'LAGMA',
  'BISHNUPUR SARLAHI',
  'MAJHGAUN KAMAHARIYA',
  'MAHESHPUR THUTHIBARI',
  'HARKAPUR 16 NO'
);

-- ============================================
-- TIER 4: Rs. 195 / Rs. 145 (Extended Regional)
-- ============================================
UPDATE ncm_branches SET shipping_rate = 195, office_pickup_rate = 145 
WHERE branch_name IN (
  'KHANDANDA',
  'MANPUR MAINAPOKHAR',
  'DUDUWA',
  'SYAULE BAZAR KAILALI',
  'BANKUL',
  'MADHOPUR',
  'BANGALACHULI',
  'BELHI CHAPENA',
  'BULINGTAR',
  'DEDGAUN',
  'HEKULI',
  'KARSIYA',
  'GERUWA',
  'PIPRAHAWA',
  'MAJHAGAWA',
  'PHALEBISAUNE',
  'NARAINAPUR BANKE',
  'BELATARI',
  'JANGRAHAWA',
  'MANJHARIYA',
  'RAGAICHA',
  'HARNAIYA SIYARI',
  'SUBARNA',
  'THORI',
  'GANESHPUR KAPILBASTU',
  'SISANIYA',
  'KHAYARMARA',
  'HATIYA',
  'GHACHOK'
);

-- ============================================
-- TIER 5: Rs. 220 / Rs. 170 (Far Regional)
-- ============================================
UPDATE ncm_branches SET shipping_rate = 220, office_pickup_rate = 170 
WHERE branch_name IN (
  'NEPALGUNJ',
  'SURKHET',
  'DHANGADHI',
  'TULSIPUR',
  'TIKAPUR',
  'LAMKI',
  'BAUNIYA',
  'GHORAHI',
  'ATTARIYA',
  'KOHALPUR',
  'SUKKHAD',
  'CHISAPANI',
  'GULARIYA',
  'SINDHULI',
  'LAMAHI',
  'DHADING BESI',
  'MANGALBARE ILAM',
  'KATARI',
  'PHARPING',
  'BHAJANI',
  'PALUNGTAR',
  'JHALARI',
  'GOPETAR',
  'CHAUMALA',
  'MASURIYA',
  'SUNDARBAZAR',
  'BESISAHAR',
  'MALEKHU',
  'DUDHAULI',
  'GAJURI',
  'KUNTABESI',
  'KHURKOT',
  'KHAJURA',
  'NARAYANPUR DANG',
  'SAMSHERGUNJ',
  'PHULBARI KAILALI',
  'BHIMPHEDI',
  'JUGEDA KAILALI',
  'KALYANPUR',
  'NAUDANDA KASKI',
  'CHAKARGHATTI SUNSARI',
  'DARBANG MYAGDI',
  'HAPURE',
  'MAHARAJGUNJ KAPILBAS',
  'AURAHI',
  'PUTALI CHOWK',
  'BIRENDRA BAZAR',
  'RAMGOPALPUR',
  'GAIR BAZAR',
  'GODETA',
  'HARIPUR',
  'SABAILA',
  'YADUKUSH',
  'TINKORIYA',
  'DHANUSADHAM',
  'NAGARAIN',
  'SAMSI',
  'RAJDEVI',
  'DAMAR CHOWK',
  'LOKAHA',
  'AURAIYA',
  'KOLHABI',
  'DHANGADHIMAI',
  'SUKHIPUR',
  'KADMAHA',
  'HANUMANNAGR',
  'JHUMKA',
  'RAJARANI',
  'DAIJEE',
  'TARATAL',
  'GALCHI',
  'TINPIPLE',
  'CHAPAKOT',
  'BHINGRI',
  'PAKADI',
  'BHAGWANPUR',
  'BASTIPUR',
  'GODAK',
  'PAHALMANPUR',
  'GETA',
  'CHYAMA',
  'JAYANAGAR',
  'JOSHIPUR',
  'HASULIYA',
  'GODAWARI KAILALI',
  'KUSHMISHERA',
  'HALESI',
  'KALAGAUDI',
  'BRAHMADEV',
  'THARMARE',
  'CHAWANNI BELDANDI',
  'DURGAULI',
  'LALJHADI',
  'GADHAWA',
  'DARVAN PYUTHAN',
  'KRISHNAPUR',
  'KHADADEVI',
  'LIKHU DHOBI',
  'MIRMIPHAT',
  'KHUDI BAZAR',
  'HOLERI',
  'BIRUWA',
  'PYUTHAN KHALANGA',
  'PAKHRIBAS',
  'SHANTINAGAR JHAPA',
  'BHEDETAR',
  'SUNJHODA',
  'BUTTABARI',
  'PHAPARBARI',
  'CHARAUDI',
  'PADAMPOKHARI',
  'BHURANG TATOPANI',
  'HATEMALO CHOWK',
  'KRISTI',
  'HARTHOK',
  'BELA',
  'SATTI'
);

-- ============================================
-- TIER 6: Rs. 245 / Rs. 195 (Remote)
-- ============================================
UPDATE ncm_branches SET shipping_rate = 245, office_pickup_rate = 195 
WHERE branch_name IN (
  'ILAM BAZAR',
  'PHIDIM',
  'MAHENDRANAGAR',
  'BHURIGAUN',
  'TAMGHAS',
  'HILE',
  'TRISHULI',
  'BIJUWAR',
  'ARYA BHANJYANG',
  'RAMPUR PALPA',
  'SANDHIKHARKA',
  'SALYAN KHALANGA',
  'DAILEKH BAZAAR',
  'BHALUWANG',
  'CHARIKOT',
  'JIRI',
  'FIKKAL',
  'MANTHALI',
  'RIDI',
  'BALETAXAR',
  'GALKOT',
  'BURTIBANG',
  'BELTAR BASAHA',
  'NEPALTAR ILAM',
  'PASHUPATINAGAR',
  'CHINCHU',
  'BHOJPUR',
  'KHANDBARI',
  'BELAURI',
  'PUNARBAS',
  'PHUNGLING',
  'DAMAN',
  'RANKE',
  'BANSGADHI',
  'MELAMCHI',
  'MYANGLUNG',
  'CHAUTARA',
  'RAJAPUR',
  'PANCHKHAL',
  'TERHATHUM BASANTAPUR',
  'DHUNCHE',
  'SHREE ANTU',
  'SIDHUWA',
  'BAHRABISE',
  'MEHELKUNA',
  'BHAKUNDEBESI',
  'DODHARA CHADANI',
  'BANI',
  'BANDIPUR',
  'BELAKA RAMPUR',
  'PHALEBAS',
  'DANABARI',
  'WAMITAKSAR',
  'MANAKAMANA',
  'BARPAK',
  'JOGBUDA',
  'RAMECHHAP BAZAR',
  'LUHAM',
  'DINGLA',
  'TARAKHOLA',
  'BUDAR',
  'SINGATI',
  'KANYAM',
  'AMARAI ARGHAKHANCHI',
  'KAMAL BAZAR',
  'BAGTHALA',
  'LATINATH',
  'GADDA CHAUKI',
  'DULLU',
  'MUKTINATH MUSTANG',
  'THARPU TANAHUN',
  'PUMDI POKHARA',
  'BAISJANGAR TANAHUN',
  'HARINAS TANAHUN',
  'ARJUNCHAUPARI SYNGJA',
  'DANDA BAZAR',
  'PILUWA',
  'RATANPUR',
  'CHAKCHAKE',
  'BIBLATE BAZAR',
  'MANEBHANJYANG',
  'MAKWANPURGADHI',
  'CHAUGHADA BAZAR',
  'BADIGAD',
  'JIWAKHOLA',
  'BIRBAS',
  'SIMALTARI',
  'CHIDIKA',
  'GHARTIGAAUN',
  'MAJUWA',
  'NALAGAD KALIMATI'
);

-- ============================================
-- TIER 7: Rs. 250 / Rs. 200 (Special)
-- ============================================
UPDATE ncm_branches SET shipping_rate = 250, office_pickup_rate = 200 
WHERE branch_name IN (
  'DUIPIPLE'
);

-- ============================================
-- TIER 8: Rs. 270 / Rs. 220 (Very Remote)
-- ============================================
UPDATE ncm_branches SET shipping_rate = 270, office_pickup_rate = 220 
WHERE branch_name IN (
  'DHANKUTA BAZAAR',
  'AMARGADHI',
  'MARTADI',
  'SIMIKOT',
  'LIWANG',
  'JUMLA',
  'MUSIKOT',
  'SHANTIPUR',
  'CHAINPUR BAJHANG',
  'NAMCHE BAZAR',
  'LUKLA',
  'DIPAYAL',
  'SANFEBAGAR',
  'DARCHULA KHALANGA',
  'GOTHALAPANI',
  'OKHALDHUNGA',
  'DIKTEL',
  'SALLERI',
  'RUKUMKOT',
  'JAJARKOT KHALANGA',
  'MANMA',
  'GAMGADHI',
  'CHAME',
  'DUNAI',
  'JOMSOM',
  'CHAINPUR SANKHUWASAB',
  'MANGALSEN',
  'GOKULESHWOR',
  'TUMLINGTAR',
  'CHAURJAHARI',
  'PATAN BAITADI',
  'SULICHAUR',
  'MARPHA MUSTANG',
  'SALLI BAZAR',
  'KOLTI',
  'BAMKA',
  'BITTHAD',
  'SILGADHI'
);

-- ============================================
-- Verify updates
-- ============================================
-- After running, execute these queries to verify:
-- SELECT shipping_rate, office_pickup_rate, COUNT(*) FROM ncm_branches GROUP BY shipping_rate, office_pickup_rate ORDER BY shipping_rate;
-- SELECT COUNT(*) FROM ncm_branches WHERE shipping_rate = 150;  -- Should be 0 or minimal

-- ============================================
-- Notes:
-- ============================================
-- 1. Some branch names in the database may have slight variations (e.g., "BASTIPUR MAKAWANPUR" vs "BASTIPUR")
-- 2. Run individual tier updates if needed to handle naming variations
-- 3. Default fallback rate remains Rs. 150 / Rs. 120 for any unmatched branches
