-- Update branches with actual NCM Home Delivery rates from Chitwan (Narayanghat)
-- Data extracted from official NCM rate card for Branch2Door delivery (2kg minimum)

-- Tier 1: Rs. 120 (Nearby/Local)
UPDATE ncm_branches SET shipping_rate = 120, estimated_days = '1-2 days'
WHERE UPPER(branch_name) IN (
  'CHITWAN', 'HETAUDA', 'BIRGUNJ', 'BASANTAPUR BAZAR', 'CHANAULI', 
  'KHAIRAHANI', 'GARUDA', 'BHANDARA', 'KURINTAR', 'POKHARIYA',
  'GAUR', 'DUMKIBAS', 'ARUNKHOLA', 'MANAHARI', 'RAJAHAR', 'CHORMARA',
  'DALDALE', 'CHANDRANIGAHAPUR', 'SIMARA', 'NIJGADH', 'KALAIYA',
  'GAIDAKOT', 'TANDI', 'KAWASOTI', 'SHAKTIKHOR'
);

-- Tier 2: Rs. 170 (Major Cities)
UPDATE ncm_branches SET shipping_rate = 170, estimated_days = '2-3 days'
WHERE UPPER(branch_name) IN (
  'TINKUNE', 'NEWROAD', 'NAYA BUSPARK', 'KALANKI', 'CHABAHIL',
  'POKHARA', 'BIRATNAGAR', 'ITAHARI', 'BUTWAL', 'BHAIRAHAWA',
  'DHARKE', 'NAGARKOT', 'PURANCHAUR', 'PAME', 'SURYABINAYAK',
  'ANBUKHAIRENI', 'JOGIKUTI', 'MANIGRAM', 'LEKHNATH', 'BANEPA',
  'PANAUTI', 'DHULIKHEL'
);

-- Tier 3: Rs. 175 (Regional Towns)
UPDATE ncm_branches SET shipping_rate = 175, estimated_days = '3-4 days'
WHERE UPPER(branch_name) IN (
  'BARJU', 'AMARDAHA', 'KERABARI MORANG', 'CHARAALI', 'JUGLE',
  'KERKHA BAZAR', 'DAMRABHITTA', 'KHAIRENI RUPANDEHI', 'BAYALBAS',
  'PATICHAUR', 'SHIVAGUNJ', 'BAHUNDANGI', 'MIRCHAIYA', 'JITPUR CHARNUMBER',
  'DULEGAUDA', 'CHATARA', 'KALABANJAR', 'SIRAHA', 'BHIMAD', 'LETANG',
  'KHUDUNABARI', 'RUPNAGAR', 'FATTEPUR', 'DHAKDAI', 'GOPIGUNJ JAMUNIYA',
  'MALANGWA', 'GALYANG', 'HARIWON', 'PATHARI', 'MADHUMALLA', 'RAJGADH',
  'GAURIGANJ', 'BANIYANI', 'MOTIPUR', 'LUMBINI', 'KOTIHAWA', 'PHEDIKHOLA',
  'SAKUWA MAHENDRANAGAR', 'KANCHIBAJAR', 'HEMJA', 'JHILJHILE', 'BELDANGI',
  'AMUWA', 'MURGIYA', 'KRISHNANAGAR', 'GOLBAZAR', 'SHARANAMATI', 'JALESHWOR',
  'TAMNAGAR', 'BUDHABARE', 'DUHABI', 'GAURADAHA', 'BELBARI', 'GAIGHAT',
  'PHARSATIKAR', 'LALBANDI', 'PUTALIBAZAR', 'PARASI', 'RANGELI', 'CHANDRAUTA',
  'TAULIHAWA', 'SURUNGA', 'DHULABARI', 'KAKARBHITTA', 'KUSHMA', 'WALING',
  'BARDIBAS', 'BENI', 'BAGLUNG', 'INARUWA', 'DUMRE', 'BARDAGHAT', 'SUNAWAL',
  'DAMAULI', 'LAHAN', 'RAJBIRAJ', 'URLABARI', 'BIRATCHOWK', 'DAMAK',
  'DHALKEBAR', 'JANAKPUR', 'BHADRAPUR', 'BIRTAMOD', 'DHARAN', 'GAUSHALA'
);

-- Tier 4: Rs. 220 (Further Regions)
UPDATE ncm_branches SET shipping_rate = 220, estimated_days = '4-5 days'
WHERE UPPER(branch_name) IN (
  'GODAK', 'BASTIPUR', 'BHAGWANPUR', 'PAKADI', 'BHINGRI', 'CHAPAKOT',
  'TINPIPLE', 'GALCHI', 'TARATAL', 'DAIJEE', 'RAJARANI', 'JHUMKA',
  'HANUMANNAGR', 'KADMAHA', 'SUKHIPUR', 'DHANGADHIMAI', 'KOLHABI',
  'AURAIYA', 'LOKAHA', 'DAMAR CHOWK', 'RAJDEVI', 'SAMSI', 'NAGARAIN',
  'DHANUSADHAM', 'TINKORIYA', 'YADUKUSH', 'SABAILA', 'HARIPUR', 'GODETA',
  'GAIR BAZAR', 'RAMGOPALPUR', 'BIRENDRA BAZAR', 'PUTALI CHOWK', 'AURAHI',
  'HAPURE', 'DARBANG', 'CHAKARGHATTI', 'NAUDANDA KASKI', 'KALYANPUR',
  'BARAHATHAWA', 'BHIMPHEDI', 'DUDHAULI', 'SINDHULI', 'LAMAHI', 'PHARPING',
  'KOHALPUR', 'ATTARIYA', 'GHORAHI', 'BAUNIYA', 'PALPA', 'TULSIPUR',
  'DHANGADHI', 'SURKHET', 'NEPALGUNJ'
);

-- Tier 5: Rs. 245 (Remote Regions)
UPDATE ncm_branches SET shipping_rate = 245, estimated_days = '5-7 days'
WHERE UPPER(branch_name) IN (
  'BARPAK', 'MANAKAMANA', 'MAHARAJGUNJ KAPILBAS', 'WAMITAKSAR', 'DANABARI',
  'PHALEBAS', 'JUGEDA', 'BELAKA RAMPUR', 'BANDIPUR', 'BANI', 'DODHARA CHADANI',
  'BHAKUNDEBESI', 'KHURKOT', 'KUNTABESI', 'BAHRABISE', 'GAJURI', 'SHREE ANTU',
  'PANCHKHAL', 'RAJAPUR', 'CHAUTARA', 'MELAMCHI', 'BANSGADHI', 'GOPETAR',
  'RANKE', 'TAPLEJUNG', 'PUNARBAS', 'BELAURI', 'KATARI', 'CHINCHU',
  'PASHUPATINAGAR', 'MANGALBARE', 'NEPALTAR BAZAR', 'MALEKHU', 'GALKOT',
  'BALETAXAR', 'DHADING BESI', 'RIDI', 'MANTHALI', 'FIKKAL', 'JIRI',
  'CHARIKOT', 'BHALUWANG', 'SALYAN KHALANGA', 'SANDHIKHARKA', 'RAMPUR',
  'ARYA BHANJYANG', 'TRISHULI', 'GULARIYA', 'TAMGHAS', 'BHURIGAUN',
  'CHISAPANI', 'MAHENDRANAGAR', 'PHIDIM', 'ILAM'
);

-- Tier 6: Rs. 270 (Remote Mountain)
UPDATE ncm_branches SET shipping_rate = 270, estimated_days = '5-7 days'
WHERE UPPER(branch_name) IN (
  'SULICHAUR', 'PATAN BAITADI', 'SAMSHERGUNJ', 'NARAYANPUR', 'KHAJURA',
  'MEHELKUNA', 'SIDHUWA', 'SALLERI', 'DIKTEL', 'SUNDARBAZAR', 'OKHALDHUNGA',
  'MASURIYA', 'CHAUMALA', 'JHALARI', 'DAMAN', 'PALUNGTAR', 'DHUNCHE',
  'BELTAR BASAHA', 'BESISAHAR', 'BURTIBANG', 'SHANTIPUR', 'LIWANG',
  'GORKHA', 'AMARGADHI', 'DAILEKH BAZAAR', 'BIJUWAR', 'DHANKUTA BAZAAR'
);

-- Tier 7: Rs. 295 (Very Remote)
UPDATE ncm_branches SET shipping_rate = 295, estimated_days = '7-10 days'
WHERE UPPER(branch_name) IN (
  'PHULBARI KAILALI', 'DUIPIPLE', 'CHAURJAHARI', 'TUMLINGTAR',
  'GOKULESHWOR', 'MANGALSEN', 'CHAINPUR SANKHUWASAB', 'JOMSOM', 'DUNAI',
  'CHAME', 'GAMGADHI', 'MANMA', 'JAJARKOT KHALANGA', 'TERHATHUM BASANTAPUR',
  'RUKUMKOT', 'SANFEBAGAR', 'DIPAYAL SILGADHI', 'KHANDBARI', 'BHOJPUR',
  'MUSIKOT', 'HILE', 'MYANGLUNG'
);

-- Tier 8: Rs. 320 (Most Remote)
UPDATE ncm_branches SET shipping_rate = 320, estimated_days = '7-14 days'
WHERE UPPER(branch_name) IN (
  'GOTHALAPANI', 'DARCHULA KHALANGA', 'LUKLA', 'NAMCHE BAZAR',
  'CHAINPUR BAJHANG', 'SIMIKOT', 'MARTADI'
);

-- Special rates
UPDATE ncm_branches SET shipping_rate = 246, estimated_days = '5-7 days'
WHERE UPPER(branch_name) IN ('BHAJANI', 'SUKKHAD', 'LAMKI', 'TIKAPUR');

UPDATE ncm_branches SET shipping_rate = 315, estimated_days = '7-10 days'
WHERE UPPER(branch_name) = 'JUMLA';