-- Update NCM branch shipping rates from official rate card (Source: NARAYANGHAT/CHITWAN)
-- Home Delivery = shipping_rate, Office Delivery = office_pickup_rate

-- ========== Tier 1: Rs. 120 / 70 (Nearby) ==========
UPDATE ncm_branches SET shipping_rate = 120, office_pickup_rate = 70 
WHERE branch_name IN (
  'CHITWAN', 'NARAYANGHAT', 'HETAUDA', 'BIRGUNJ', 'SIMARA', 'GAIDAKOT', 'TANDI', 
  'KAWASOTI', 'DUMKIBAS', 'ARUNKHOLA', 'MANAHARI', 'NIJGADH', 'KALAIYA', 'POKHARIYA', 
  'SHAKTIKHOR', 'GAUR', 'CHANDRANIGAHAPUR', 'BHANDARA', 'KURINTAR', 'BASANTAPUR BAZAR', 
  'CHANAULI', 'KHAIRAHANI', 'GARUDA', 'RAJAHAR', 'CHORMARA', 'DALDALE'
);

-- ========== Tier 2: Rs. 170 / 120 (Major Cities) ==========
UPDATE ncm_branches SET shipping_rate = 170, office_pickup_rate = 120 
WHERE branch_name IN (
  'TINKUNE', 'BUTWAL', 'BHAIRAHAWA', 'BIRATNAGAR', 'ITAHARI', 'POKHARA', 'LEKHNATH', 
  'BANEPA', 'DHULIKHEL', 'PANAUTI', 'JOGIKUTI', 'DHARKE', 'NAGARKOT', 'PURANCHAUR', 
  'PAME', 'ANBUKHAIRENI', 'CHABAHIL', 'KALANKI', 'MANIGRAM', 'NEWROAD', 'NAYA BUSPARK', 
  'SURYABINAYAK'
);

-- ========== Tier 3: Rs. 175 / 125 (Regional) ==========
UPDATE ncm_branches SET shipping_rate = 175, office_pickup_rate = 125 
WHERE branch_name IN (
  'DHARAN', 'DAMAK', 'BIRTAMOD', 'BHADRAPUR', 'JANAKPUR', 'RAJBIRAJ', 'LAHAN', 
  'URLABARI', 'BIRATCHOWK', 'BELBARI', 'KAKARBHITTA', 'DHULABARI', 'SURUNGA', 
  'SIRAHA', 'GAIGHAT', 'BARDIBAS', 'LALBANDI', 'GOLBAZAR', 'CHATARA', 'LETANG', 
  'INARUWA', 'DUHABI', 'BUDHABARE', 'RANGELI', 'PARASI', 'TAULIHAWA', 'CHANDRAUTA', 
  'LUMBINI', 'WALING', 'KUSHMA', 'BENI', 'BAGLUNG', 'DUMRE', 'DAMAULI', 'HEMJA', 
  'PUTALIBAZAR', 'GALYANG', 'BARDAGHAT', 'SUNAWAL', 'KRISHNANAGAR', 'RAJGADH', 
  'GAURIGANJ', 'MALANGWA', 'BARJU', 'AMARDAHA', 'KERABARI MORANG', 'CHARAALI', 
  'JUGLE', 'KERKHA BAZAR', 'DAMRABHITTA', 'BAYALBAS', 'PATICHAUR', 'SHIVAGUNJ', 
  'BAHUNDANGI', 'MIRCHAIYA', 'JITPUR CHARNUMBER', 'PATHARI', 'HARIWON', 'MADHUMALLA', 
  'BANIYANI', 'MOTIPUR', 'PHARSATIKAR', 'KHUDUNABARI', 'PHEDIKHOLA', 'KOTIHAWA', 
  'BELDANGI', 'JHILJHILE', 'KANCHIBAJAR', 'SAKUWA MAHENDRANAGAR', 'AMUWA', 'MURGIYA', 
  'SHARANAMATI', 'TAMNAGAR', 'JALESHWOR', 'DHAKDAI', 'GOPIGUNJ JAMUNIYA', 'FATTEPUR', 
  'RUPNAGAR', 'BHIMAD', 'DULEGAUDA', 'KALABANJAR', 'GAURADAHA', 'GAUSHALA', 
  'DHALKEBAR', 'DEVTAL BENAULI', 'KHAIRENI RUPANDEHI'
);

-- ========== Tier 4: Rs. 220 / 170 (Further) ==========
UPDATE ncm_branches SET shipping_rate = 220, office_pickup_rate = 170 
WHERE branch_name IN (
  'DHANGADHI', 'NEPALGUNJ', 'TULSIPUR', 'GHORAHI', 'SURKHET', 'KOHALPUR', 'ATTARIYA', 
  'PALPA', 'BAUNIYA', 'SINDHULI', 'DUDHAULI', 'LAMAHI', 'PHARPING', 'GODAK', 
  'BASTIPUR', 'BHAGWANPUR', 'PAKADI', 'BHINGRI', 'CHAPAKOT', 'TINPIPLE', 'GALCHI', 
  'TARATAL', 'DAIJEE', 'RAJARANI', 'JHUMKA', 'HANUMANNAGR', 'KADMAHA', 'SUKHIPUR', 
  'DHANGADHIMAI', 'KOLHABI', 'AURAIYA', 'LOKAHA', 'DAMAR CHOWK', 'RAJDEVI', 'SAMSI', 
  'NAGARAIN', 'DHANUSADHAM', 'TINKORIYA', 'YADUKUSH', 'SABAILA', 'HARIPUR', 'GODETA', 
  'GAIR BAZAR', 'RAMGOPALPUR', 'BIRENDRA BAZAR', 'PUTALI CHOWK', 'AURAHI', 'HAPURE', 
  'DARBANG', 'CHAKARGHATTI', 'NAUDANDA KASKI', 'KALYANPUR', 'BARAHATHAWA', 'BHIMPHEDI'
);

-- ========== Tier 5: Rs. 245 / 195 (Remote) ==========
UPDATE ncm_branches SET shipping_rate = 245, office_pickup_rate = 195 
WHERE branch_name IN (
  'BARPAK', 'MANAKAMANA', 'ILAM', 'PHIDIM', 'TAPLEJUNG', 'TRISHULI', 'DHADING BESI', 
  'MELAMCHI', 'CHAUTARA', 'PANCHKHAL', 'GALKOT', 'MALEKHU', 'BAHRABISE', 'GAJURI', 
  'KHURKOT', 'KUNTABESI', 'CHARIKOT', 'JIRI', 'FIKKAL', 'MANTHALI', 'KATARI', 
  'PASHUPATINAGAR', 'MANGALBARE', 'NEPALTAR BAZAR', 'BANDIPUR', 'BELAKA RAMPUR', 
  'JUGEDA', 'PHALEBAS', 'DANABARI', 'BHAKUNDEBESI', 'SHREE ANTU', 'PUNARBAS', 
  'BELAURI', 'BANSGADHI', 'GOPETAR', 'RANKE', 'CHISAPANI', 'MAHENDRANAGAR', 
  'SALYAN KHALANGA', 'SANDHIKHARKA', 'ARYA BHANJYANG', 'GULARIYA', 'TAMGHAS', 
  'BHURIGAUN', 'RAJAPUR', 'RIDI', 'BHALUWANG', 'BALETAXAR', 'RAMPUR', 'CHINCHU', 
  'MAHARAJGUNJ KAPILBAS', 'WAMITAKSAR'
);

-- ========== Tier 5b: Rs. 246 / 196 (Special Remote) ==========
UPDATE ncm_branches SET shipping_rate = 246, office_pickup_rate = 196 
WHERE branch_name IN ('BHAJANI', 'SUKKHAD', 'LAMKI', 'TIKAPUR');

-- ========== Tier 6: Rs. 270 / 220 (Very Remote) ==========
UPDATE ncm_branches SET shipping_rate = 270, office_pickup_rate = 220 
WHERE branch_name IN (
  'DHUNCHE', 'SALLERI', 'DIKTEL', 'SUNDARBAZAR', 'OKHALDHUNGA', 'MASURIYA', 
  'DHANKUTA BAZAAR', 'CHAUMALA', 'JHALARI', 'DAMAN', 'PALUNGTAR', 'DAILEKH BAZAAR', 
  'AMARGADHI', 'GORKHA', 'LIWANG', 'BIJUWAR', 'BURTIBANG', 'BESISAHAR', 'BELTAR BASAHA', 
  'SHANTIPUR', 'SULICHAUR', 'PATAN BAITADI', 'SAMSHERGUNJ', 'NARAYANPUR', 'KHAJURA', 
  'MEHELKUNA', 'SIDHUWA'
);

-- ========== Tier 7: Rs. 295 / 245 (Most Remote) ==========
UPDATE ncm_branches SET shipping_rate = 295, office_pickup_rate = 245 
WHERE branch_name IN (
  'KHANDBARI', 'BHOJPUR', 'MYANGLUNG', 'HILE', 'TUMLINGTAR', 'CHAINPUR SANKHUWASAB', 
  'JOMSOM', 'DUNAI', 'CHAME', 'GAMGADHI', 'MANMA', 'JAJARKOT KHALANGA', 'RUKUMKOT', 
  'TERHATHUM BASANTAPUR', 'MANGALSEN', 'SANFEBAGAR', 'DIPAYAL SILGADHI', 'CHAURJAHARI', 
  'PHULBARI KAILALI', 'DUIPIPLE', 'MUSIKOT', 'BANI', 'DODHARA CHADANI', 'GOKULESHWOR'
);

-- ========== Tier 8: Rs. 315-320 / 265-270 (Extreme Remote) ==========
UPDATE ncm_branches SET shipping_rate = 315, office_pickup_rate = 265 
WHERE branch_name = 'JUMLA';

UPDATE ncm_branches SET shipping_rate = 320, office_pickup_rate = 270 
WHERE branch_name IN (
  'LUKLA', 'NAMCHE BAZAR', 'SIMIKOT', 'MARTADI', 'GOTHALAPANI', 'DARCHULA KHALANGA',
  'CHAINPUR BAJHANG'
);