-- Add office_pickup_rate column to ncm_branches
ALTER TABLE ncm_branches ADD COLUMN IF NOT EXISTS office_pickup_rate integer DEFAULT NULL;

-- Populate office pickup rates (Rs. 50 less than home delivery rates)

-- Tier 1: Rs. 70 (Nearby/Local - home delivery was Rs. 120)
UPDATE ncm_branches SET office_pickup_rate = 70
WHERE UPPER(branch_name) IN (
  'CHITWAN', 'HETAUDA', 'BIRGUNJ', 'BASANTAPUR BAZAR', 'CHANAULI', 
  'KHAIRAHANI', 'GARUDA', 'BHANDARA', 'KURINTAR', 'POKHARIYA',
  'GAUR', 'DUMKIBAS', 'ARUNKHOLA', 'MANAHARI', 'RAJAHAR', 'CHORMARA',
  'DALDALE', 'CHANDRANIGAHAPUR', 'SIMARA', 'NIJGADH', 'KALAIYA',
  'GAIDAKOT', 'TANDI', 'KAWASOTI', 'SHAKTIKHOR', 'NARAYANGHAT'
);

-- Tier 2: Rs. 120 (Major Cities - home delivery was Rs. 170)
UPDATE ncm_branches SET office_pickup_rate = 120
WHERE UPPER(branch_name) IN (
  'TINKUNE', 'NEWROAD', 'NAYA BUSPARK', 'KALANKI', 'CHABAHIL',
  'POKHARA', 'BIRATNAGAR', 'ITAHARI', 'BUTWAL', 'BHAIRAHAWA',
  'DHARKE', 'NAGARKOT', 'PURANCHAUR', 'PAME', 'SURYABINAYAK',
  'ANBUKHAIRENI', 'JOGIKUTI', 'MANIGRAM', 'LEKHNATH', 'BANEPA',
  'PANAUTI', 'DHULIKHEL'
);

-- Tier 3: Rs. 125 (Regional Towns - home delivery was Rs. 175)
UPDATE ncm_branches SET office_pickup_rate = 125
WHERE UPPER(branch_name) IN (
  'BARJU', 'AMARDAHA', 'KERABARI MORANG', 'CHARAALI', 'JUGLE',
  'KERKHA BAZAR', 'DAMRABHITTA', 'KHAIRENI RUPANDEHI', 'BAYALBAS',
  'PATICHAUR', 'SHIVAGUNJ', 'BAHUNDANGI', 'MIRCHAIYA', 'JITPUR CHARNUMBER',
  'DULEGAUDA', 'CHATARA', 'KALABANJAR', 'SIRAHA', 'BHIMAD', 'LETANG',
  'KHUDUNABARI', 'RUPNAGAR', 'FATTEPUR', 'DHAKDAI', 'GOPIGUNJ JAMUNIYA',
  'MALANGWA', 'GALYANG', 'HARIWON', 'PATHARI', 'MADHUMALLA', 'RAJGADH',
  'GAURIGANJ', 'BANIYANI', 'MOTIPUR', 'LUMBINI', 'KOTIHAWA', 'PHEDIKHOLA',
  'SAKUWA MAHENDRANAGAR', 'KANCHIBAJAR', 'HEMJA', 'JHILJHILE', 'BELDANGI',
  'AMUWA', 'MURGIYA', 'KRISHNANAGAR', 'GOLBAZAR', 'SHARANAMATI', 'JALESHWOR',
  'TAMNAGAR', 'BUDHABARE', 'DUHABI', 'GAURADAHA', 'BELBARI', 'GAIGHAT',
  'PHARSATIKAR', 'LALBANDI', 'PUTALIBAZAR', 'PARASI', 'RANGELI', 'CHANDRAUTA',
  'TAULIHAWA', 'SURUNGA', 'DHULABARI', 'KAKARBHITTA', 'KUSHMA', 'WALING',
  'BARDIBAS', 'BENI', 'BAGLUNG', 'INARUWA', 'DUMRE', 'BARDAGHAT', 'SUNAWAL',
  'DAMAULI', 'LAHAN', 'RAJBIRAJ', 'URLABARI', 'BIRATCHOWK', 'DAMAK',
  'DHALKEBAR', 'JANAKPUR', 'BHADRAPUR', 'BIRTAMOD', 'DHARAN', 'GAUSHALA'
);

-- Tier 4: Rs. 170 (Further Regions - home delivery was Rs. 220)
UPDATE ncm_branches SET office_pickup_rate = 170
WHERE UPPER(branch_name) IN (
  'GODAK', 'BASTIPUR', 'BHAGWANPUR', 'PAKADI', 'BHINGRI', 'CHAPAKOT',
  'TINPIPLE', 'GALCHI', 'TARATAL', 'DAIJEE', 'RAJARANI', 'JHUMKA',
  'HANUMANNAGR', 'KADMAHA', 'SUKHIPUR', 'DHANGADHIMAI', 'KOLHABI',
  'AURAIYA', 'LOKAHA', 'DAMAR CHOWK', 'RAJDEVI', 'SAMSI', 'NAGARAIN',
  'DHANUSADHAM', 'TINKORIYA', 'YADUKUSH', 'SABAILA', 'HARIPUR', 'GODETA',
  'GAIR BAZAR', 'RAMGOPALPUR', 'BIRENDRA BAZAR', 'PUTALI CHOWK', 'AURAHI',
  'HAPURE', 'DARBANG', 'CHAKARGHATTI', 'NAUDANDA KASKI', 'KALYANPUR',
  'BARAHATHAWA', 'BHIMPHEDI', 'DUDHAULI', 'SINDHULI', 'LAMAHI', 'PHARPING',
  'KOHALPUR', 'ATTARIYA', 'GHORAHI', 'BAUNIYA', 'PALPA', 'TULSIPUR',
  'DHANGADHI', 'SURKHET', 'NEPALGUNJ'
);

-- Tier 5: Rs. 195 (Remote Regions - home delivery was Rs. 245)
UPDATE ncm_branches SET office_pickup_rate = 195
WHERE UPPER(branch_name) IN (
  'BARPAK', 'MANAKAMANA', 'MAHARAJGUNJ KAPILBAS', 'WAMITAKSAR', 'DANABARI',
  'PHALEBAS', 'JUGEDA', 'BELAKA RAMPUR', 'BANDIPUR', 'BANI', 'DODHARA CHADANI',
  'BHAKUNDEBESI', 'KHURKOT', 'KUNTABESI', 'BAHRABISE', 'GAJURI', 'SHREE ANTU',
  'PANCHKHAL', 'RAJAPUR', 'CHAUTARA', 'MELAMCHI', 'BANSGADHI', 'GOPETAR',
  'RANKE', 'TAPLEJUNG', 'PUNARBAS', 'BELAURI', 'KATARI', 'CHINCHU',
  'PASHUPATINAGAR', 'MANGALBARE', 'NEPALTAR BAZAR', 'MALEKHU', 'GALKOT',
  'BALETAXAR', 'DHADING BESI', 'RIDI', 'MANTHALI', 'FIKKAL', 'JIRI',
  'CHARIKOT', 'BHALUWANG', 'SALYAN KHALANGA', 'SANDHIKHARKA', 'RAMPUR',
  'ARYA BHANJYANG', 'TRISHULI', 'GULARIYA', 'TAMGHAS', 'BHURIGAUN',
  'CHISAPANI', 'MAHENDRANAGAR', 'PHIDIM', 'ILAM', 'BHAJANI', 'SUKKHAD', 
  'LAMKI', 'TIKAPUR'
);

-- Tier 6: Rs. 220 (Remote Mountain - home delivery was Rs. 270)
UPDATE ncm_branches SET office_pickup_rate = 220
WHERE UPPER(branch_name) IN (
  'SULICHAUR', 'PATAN BAITADI', 'SAMSHERGUNJ', 'NARAYANPUR', 'KHAJURA',
  'MEHELKUNA', 'SIDHUWA', 'SALLERI', 'DIKTEL', 'SUNDARBAZAR', 'OKHALDHUNGA',
  'MASURIYA', 'CHAUMALA', 'JHALARI', 'DAMAN', 'PALUNGTAR', 'DHUNCHE',
  'BELTAR BASAHA', 'BESISAHAR', 'BURTIBANG', 'SHANTIPUR', 'LIWANG',
  'GORKHA', 'AMARGADHI', 'DAILEKH BAZAAR', 'BIJUWAR', 'DHANKUTA BAZAAR'
);

-- Tier 7: Rs. 245 (Very Remote - home delivery was Rs. 295)
UPDATE ncm_branches SET office_pickup_rate = 245
WHERE UPPER(branch_name) IN (
  'PHULBARI KAILALI', 'DUIPIPLE', 'CHAURJAHARI', 'TUMLINGTAR',
  'GOKULESHWOR', 'MANGALSEN', 'CHAINPUR SANKHUWASAB', 'JOMSOM', 'DUNAI',
  'CHAME', 'GAMGADHI', 'MANMA', 'JAJARKOT KHALANGA', 'TERHATHUM BASANTAPUR',
  'RUKUMKOT', 'SANFEBAGAR', 'DIPAYAL SILGADHI', 'KHANDBARI', 'BHOJPUR',
  'MUSIKOT', 'HILE', 'MYANGLUNG'
);

-- Tier 8: Rs. 265-270 (Most Remote - home delivery was Rs. 315-320)
UPDATE ncm_branches SET office_pickup_rate = 265
WHERE UPPER(branch_name) = 'JUMLA';

UPDATE ncm_branches SET office_pickup_rate = 270
WHERE UPPER(branch_name) IN (
  'GOTHALAPANI', 'DARCHULA KHALANGA', 'LUKLA', 'NAMCHE BAZAR',
  'CHAINPUR BAJHANG', 'SIMIKOT', 'MARTADI'
);

-- Set default office_pickup_rate for any branches without specific rates
-- (shipping_rate - 50, minimum 50)
UPDATE ncm_branches 
SET office_pickup_rate = GREATEST(50, COALESCE(shipping_rate, 150) - 50)
WHERE office_pickup_rate IS NULL;